# Generated by Django 6.0 on 2026-01-16 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='EMAIL')),
                ('telegram_id', models.IntegerField(default=None, null=True, unique=True, verbose_name='TELEGRAM_ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('main_channel', models.CharField(choices=[('telegram', 'TELEGRAM'), ('email', 'EMAIL')], default='email', verbose_name='Основной канал уведомлений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку')),
                ('external_id', models.IntegerField(verbose_name='EXTERNAL_ID')),
                ('source', models.CharField(choices=[('TVMaze', 'TVMAZE')], max_length=25, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус мониторинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_title_source_external')],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('season', models.IntegerField(blank=True, null=True, verbose_name='Сезон')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('external_release_id', models.IntegerField(verbose_name='EXTERNAL_ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='radar.title', verbose_name='Тайтл')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_channel', models.CharField(choices=[('telegram', 'TELEGRAM'), ('email', 'EMAIL')], max_length=24, verbose_name='Канал уведомлений')),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('error', 'Error'), ('await', 'Await')], default='await', verbose_name='Статус уведомления')),
                ('sent_at', models.DateTimeField(default=None, null=True, verbose_name='Дата отправления')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='radar.profile', verbose_name='Профиль')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_logs', to='radar.release', verbose_name='Релиз')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='radar.title', verbose_name='Тайтл')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус мониторинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('last_notified_release', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='radar.release', verbose_name='Последнее уведомление о релизе')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='radar.profile', verbose_name='Профиль')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='radar.title', verbose_name='Тайтл')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'title'), name='uniq_subscription_profile_title')],
            },
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('title', 'external_release_id'), name='uniq_release_title_external'),
        ),
    ]
