# Generated by Django 6.0 on 2026-01-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='EMAIL')),
                ('telegram_id', models.IntegerField(default=None, null=True, unique=True, verbose_name='TELEGRAM_ID')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('main_channel', models.CharField(choices=[('telegram', 'TELEGRAM'), ('email', 'EMAIL')], default='email', verbose_name='Основной канал уведомлений')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='uniq_subscription_user_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='radar.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='radar.profile', verbose_name='Профиль'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('profile', 'title'), name='uniq_subscription_profile_title'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
